


const testData = [
        {
          "id": 1,
          "cptyName": "Scania",
          "Pair": "SEKUSD",
          "date": "2018/10/18 16:38:6",
          "side": "buy",
          "riskAmount": 840064442,
          "status": "OC",
          "type": "fwd",
          "info": "RULE",
          "test": 0.1,
          "margin": 0.06,
          "earnings": 0
        },
        {
          "id": 2,
          "cptyName": "Scania",
          "Pair": "USDSEK",
          "date": "2018/2/8 24:8:13",
          "side": "sell",
          "riskAmount": 607470686,
          "status": "OC",
          "type": "swp",
          "info": "RULE",
          "test": 0.2,
          "margin": 0.06,
          "earnings": 0
        },
        {
          "id": 3,
          "cptyName": "Scania",
          "Pair": "EURSEK",
          "date": "2018/5/1 18:57:53",
          "side": "buy",
          "riskAmount": 733031102,
          "status": "OC",
          "type": "sp",
          "info": "RULE",
          "test": 0.3,
          "margin": 0.04,
          "earnings": 0
        },
        {
          "id": 4,
          "cptyName": "Scania",
          "Pair": "USDSEK",
          "date": "2018/3/21 21:26:28",
          "side": "sell",
          "riskAmount": 345405213,
          "status": "OC",
          "type": "fwd",
          "info": "RULE",
          "test": 0.4,
          "margin": 0.05,
          "earnings": 0
        },
        {
          "id": 5,
          "cptyName": "Scania",
          "Pair": "EURSEK",
          "date": "2018/1/21 2:32:51",
          "side": "buy",
          "riskAmount": 279622366,
          "status": "OC",
          "type": "swp",
          "info": "RULE",
          "test": 0.5,
          "margin": 0.03,
          "earnings": 0
        },
        {
          "id": 6,
          "cptyName": "Scania",
          "Pair": "EURUSD",
          "date": "2018/9/26 14:37:1",
          "side": "sell",
          "riskAmount": 694564124,
          "status": "OC",
          "type": "sp",
          "info": "RULE",
          "test": 0.6,
          "margin": 0.05,
          "earnings": 0
        },
        {
          "id": 7,
          "cptyName": "Scania",
          "Pair": "SEKUSD",
          "date": "2018/8/6 22:59:58",
          "side": "buy",
          "riskAmount": 489906804,
          "status": "OC",
          "type": "fwd",
          "info": "RULE",
          "test": 0.7,
          "margin": 0.01,
          "earnings": 0
        },
        {
          "id": 8,
          "cptyName": "Scania",
          "Pair": "EURUSD",
          "date": "2018/1/28 22:4:4",
          "side": "sell",
          "riskAmount": 796580525,
          "status": "OC",
          "type": "swp",
          "info": "CANCELLED",
          "test": 0.8,
          "margin": 0.01,
          "earnings": 0
        },
        {
          "id": 9,
          "cptyName": "Scania",
          "Pair": "EURSEK",
          "date": "2018/1/27 16:26:8",
          "side": "buy",
          "riskAmount": 667180680,
          "status": "OC",
          "type": "sp",
          "info": "CANCELLED",
          "test": 0.9,
          "margin": 0.09,
          "earnings": 0
        },
        {
          "id": 10,
          "cptyName": "Scania",
          "Pair": "EURSEK",
          "date": "2018/2/8 10:56:24",
          "side": "buy",
          "riskAmount": 617670985,
          "status": "OC",
          "type": "fwd",
          "info": "CANCELLED",
          "test": 1,
          "margin": 0.07,
          "earnings": 0
        },
        {
          "id": 11,
          "cptyName": "Scania",
          "Pair": "USDEUR",
          "date": "2018/4/20 3:34:29",
          "side": "sell",
          "riskAmount": 517695070,
          "status": "OC",
          "type": "swp",
          "info": "CANCELLED",
          "test": 2,
          "margin": 0.03,
          "earnings": 0
        },
        {
          "id": 12,
          "cptyName": "Scania",
          "Pair": "USDEUR",
          "date": "2018/11/15 5:13:40",
          "side": "buy",
          "riskAmount": 926616606,
          "status": "OC",
          "type": "sp",
          "info": "CANCELLED",
          "test": 3,
          "margin": 0.06,
          "earnings": 0
        },
        {
          "id": 13,
          "cptyName": "Scania",
          "Pair": "USDSEK",
          "date": "2018/5/20 12:17:0",
          "side": "sell",
          "riskAmount": 843659009,
          "status": "OC",
          "type": "fwd",
          "info": "CANCELLED",
          "test": 4,
          "margin": 0.02,
          "earnings": 0
        },
        {
          "id": 14,
          "cptyName": "Scania",
          "Pair": "USDSEK",
          "date": "2018/1/20 9:43:12",
          "side": "buy",
          "riskAmount": 512668516,
          "status": "OC",
          "type": "swp",
          "info": "CANCELLED",
          "test": 5,
          "margin": 0.06,
          "earnings": 0
        },
        {
          "id": 15,
          "cptyName": "Scania",
          "Pair": "USDEUR",
          "date": "2018/7/12 21:43:15",
          "side": "sell",
          "riskAmount": 129495078,
          "status": "OC",
          "type": "sp",
          "info": "CANCELLED",
          "test": 6,
          "margin": 0.02,
          "earnings": 0
        },
        {
          "id": 16,
          "cptyName": "Scania",
          "Pair": "USDEUR",
          "date": "2018/12/9 16:35:5",
          "side": "buy",
          "riskAmount": 180659354,
          "status": "OC",
          "type": "fwd",
          "info": "CANCELLED",
          "test": 7,
          "margin": 0.09,
          "earnings": 0
        },
        {
          "id": 17,
          "cptyName": "Scania",
          "Pair": "EURSEK",
          "date": "2018/1/22 23:42:51",
          "side": "sell",
          "riskAmount": 899210738,
          "status": "OC",
          "type": "swp",
          "info": "CANCELLED",
          "test": 8,
          "margin": 0.06,
          "earnings": 0
        },
        {
          "id": 18,
          "cptyName": "Scania",
          "Pair": "USDSEK",
          "date": "2018/4/11 23:52:2",
          "side": "buy",
          "riskAmount": 271192063,
          "status": "OC",
          "type": "sp",
          "info": "CANCELLED",
          "test": 9,
          "margin": 0.03,
          "earnings": 0
        },
        {
          "id": 19,
          "cptyName": "Scania",
          "Pair": "USDEUR",
          "date": "2018/11/2 20:42:24",
          "side": "sell",
          "riskAmount": 150181057,
          "status": "OC",
          "type": "fwd",
          "info": "CANCELLED",
          "test": 10,
          "margin": 0.04,
          "earnings": 0
        },
        {
          "id": 20,
          "cptyName": "Scania",
          "Pair": "USDEUR",
          "date": "2018/11/12 2:34:47",
          "side": "buy",
          "riskAmount": 499267306,
          "status": "OC",
          "type": "swp",
          "info": "UNKNOWN",
          "test": 20,
          "margin": 0.02,
          "earnings": 0
        },
        {
          "id": 21,
          "cptyName": "Scania",
          "Pair": "EURSEK",
          "date": "2018/3/22 18:54:40",
          "side": "sell",
          "riskAmount": 673314493,
          "status": "OC",
          "type": "sp",
          "info": "UNKNOWN",
          "test": 30,
          "margin": 0.09,
          "earnings": 0
        },
        {
          "id": 22,
          "cptyName": "Scania",
          "Pair": "SEKUSD",
          "date": "2018/7/17 17:47:46",
          "side": "buy",
          "riskAmount": 419013226,
          "status": "OC",
          "type": "fwd",
          "info": "UNKNOWN",
          "test": 40,
          "margin": 0.09,
          "earnings": 0
        },
        {
          "id": 23,
          "cptyName": "Scania",
          "Pair": "EURSEK",
          "date": "2018/1/17 24:36:47",
          "side": "sell",
          "riskAmount": 707542458,
          "status": "OC",
          "type": "swp",
          "info": "UNKNOWN",
          "test": 50,
          "margin": 0.09,
          "earnings": 0
        },
        {
          "id": 24,
          "cptyName": "Scania",
          "Pair": "USDEUR",
          "date": "2018/2/25 22:20:9",
          "side": "buy",
          "riskAmount": 56376992,
          "status": "OC",
          "type": "sp",
          "info": "UNKNOWN",
          "test": 60,
          "margin": 0.02,
          "earnings": 0
        },
        {
          "id": 25,
          "cptyName": "Scania",
          "Pair": "USDSEK",
          "date": "2018/2/13 13:50:7",
          "side": "sell",
          "riskAmount": 89091448,
          "status": "OC",
          "type": "fwd",
          "info": "UNKNOWN",
          "test": 70,
          "margin": 0.1,
          "earnings": 0
        },
        {
          "id": 26,
          "cptyName": "Scania",
          "Pair": "USDEUR",
          "date": "2018/8/23 10:51:11",
          "side": "buy",
          "riskAmount": 715562302,
          "status": "OC",
          "type": "swp",
          "info": "UNKNOWN",
          "test": 80,
          "margin": 0.03,
          "earnings": 0
        },
        {
          "id": 27,
          "cptyName": "Scania",
          "Pair": "SEKUSD",
          "date": "2018/3/7 8:36:13",
          "side": "sell",
          "riskAmount": 693705203,
          "status": "OD",
          "type": "sp",
          "info": "",
          "test": 90,
          "margin": 0.08,
          "earnings": 55496416.24
        },
        {
          "id": 28,
          "cptyName": "Scania",
          "Pair": "USDSEK",
          "date": "2018/4/21 19:39:21",
          "side": "sell",
          "riskAmount": 996360424,
          "status": "OD",
          "type": "fwd",
          "info": "",
          "test": 100,
          "margin": 0.04,
          "earnings": 39854416.96
        },
        {
          "id": 29,
          "cptyName": "Scania",
          "Pair": "USDSEK",
          "date": "2018/1/1 6:55:3",
          "side": "buy",
          "riskAmount": 200903915,
          "status": "OD",
          "type": "swp",
          "info": "",
          "test": 200,
          "margin": 0.02,
          "earnings": 4018078.3
        },
        {
          "id": 30,
          "cptyName": "Scania",
          "Pair": "EURUSD",
          "date": "2018/8/19 24:52:16",
          "side": "sell",
          "riskAmount": 420352423,
          "status": "OD",
          "type": "sp",
          "info": "",
          "test": 300,
          "margin": 0.07,
          "earnings": 29424669.61
        },
        {
          "id": 31,
          "cptyName": "Scania",
          "Pair": "USDEUR",
          "date": "2018/2/15 14:49:33",
          "side": "buy",
          "riskAmount": 180734476,
          "status": "OD",
          "type": "fwd",
          "info": "",
          "test": 400,
          "margin": 0.07,
          "earnings": 12651413.32
        },
        {
          "id": 32,
          "cptyName": "Scania",
          "Pair": "USDEUR",
          "date": "2018/3/15 21:42:17",
          "side": "sell",
          "riskAmount": 559980201,
          "status": "OD",
          "type": "swp",
          "info": "",
          "test": 500,
          "margin": 0.09,
          "earnings": 50398218.09
        },
        {
          "id": 33,
          "cptyName": "Scania",
          "Pair": "USDEUR",
          "date": "2018/3/6 3:55:28",
          "side": "buy",
          "riskAmount": 337903686,
          "status": "OD",
          "type": "sp",
          "info": "",
          "test": 600,
          "margin": 0.01,
          "earnings": 3379036.86
        },
        {
          "id": 34,
          "cptyName": "Scania",
          "Pair": "SEKUSD",
          "date": "2018/3/18 22:52:5",
          "side": "sell",
          "riskAmount": 909871478,
          "status": "OD",
          "type": "fwd",
          "info": "",
          "test": 700,
          "margin": 0.08,
          "earnings": 72789718.24
        },
        {
          "id": 35,
          "cptyName": "Scania",
          "Pair": "USDEUR",
          "date": "2018/10/7 11:32:8",
          "side": "buy",
          "riskAmount": 746717123,
          "status": "OD",
          "type": "swp",
          "info": "",
          "test": 800,
          "margin": 0.1,
          "earnings": 74671712.3
        },
        {
          "id": 36,
          "cptyName": "Scania",
          "Pair": "USDEUR",
          "date": "2018/4/9 20:48:22",
          "side": "sell",
          "riskAmount": 82758227,
          "status": "OD",
          "type": "sp",
          "info": "",
          "test": 900,
          "margin": 0.06,
          "earnings": 4965493.62
        },
        {
          "id": 37,
          "cptyName": "Nokia",
          "Pair": "SEKUSD",
          "date": "2018/8/28 11:22:53",
          "side": "buy",
          "riskAmount": 355445494,
          "status": "OC",
          "type": "fwd",
          "info": "RULE",
          "test": 0.1,
          "margin": 0.07,
          "earnings": 0
        },
        {
          "id": 38,
          "cptyName": "Nokia",
          "Pair": "USDSEK",
          "date": "2018/12/26 6:20:47",
          "side": "sell",
          "riskAmount": 144746221,
          "status": "OC",
          "type": "swp",
          "info": "RULE",
          "test": 0.2,
          "margin": 0.08,
          "earnings": 0
        },
        {
          "id": 39,
          "cptyName": "Nokia",
          "Pair": "EURSEK",
          "date": "2018/5/13 22:7:50",
          "side": "buy",
          "riskAmount": 863765988,
          "status": "OC",
          "type": "sp",
          "info": "RULE",
          "test": 0.3,
          "margin": 0.04,
          "earnings": 0
        },
        {
          "id": 40,
          "cptyName": "Nokia",
          "Pair": "USDSEK",
          "date": "2018/11/8 17:35:45",
          "side": "sell",
          "riskAmount": 864999992,
          "status": "OC",
          "type": "fwd",
          "info": "RULE",
          "test": 0.4,
          "margin": 0.03,
          "earnings": 0
        },
        {
          "id": 41,
          "cptyName": "Nokia",
          "Pair": "EURSEK",
          "date": "2018/5/15 4:18:35",
          "side": "buy",
          "riskAmount": 387661488,
          "status": "OC",
          "type": "swp",
          "info": "RULE",
          "test": 0.5,
          "margin": 0.01,
          "earnings": 0
        },
        {
          "id": 42,
          "cptyName": "Nokia",
          "Pair": "EURUSD",
          "date": "2018/10/12 24:25:51",
          "side": "sell",
          "riskAmount": 657594430,
          "status": "OC",
          "type": "sp",
          "info": "RULE",
          "test": 0.6,
          "margin": 0.06,
          "earnings": 0
        },
        {
          "id": 43,
          "cptyName": "Nokia",
          "Pair": "SEKUSD",
          "date": "2018/4/19 12:51:21",
          "side": "buy",
          "riskAmount": 79792917,
          "status": "OC",
          "type": "fwd",
          "info": "RULE",
          "test": 0.7,
          "margin": 0.05,
          "earnings": 0
        },
        {
          "id": 44,
          "cptyName": "Nokia",
          "Pair": "EURUSD",
          "date": "2018/2/14 20:43:48",
          "side": "sell",
          "riskAmount": 291545352,
          "status": "OC",
          "type": "swp",
          "info": "CANCELLED",
          "test": 0.8,
          "margin": 0.06,
          "earnings": 0
        },
        {
          "id": 45,
          "cptyName": "Nokia",
          "Pair": "EURSEK",
          "date": "2018/8/20 23:4:41",
          "side": "buy",
          "riskAmount": 854950027,
          "status": "OC",
          "type": "sp",
          "info": "CANCELLED",
          "test": 0.9,
          "margin": 0.03,
          "earnings": 0
        },
        {
          "id": 46,
          "cptyName": "Nokia",
          "Pair": "EURSEK",
          "date": "2018/4/7 22:9:0",
          "side": "buy",
          "riskAmount": 107405016,
          "status": "OC",
          "type": "fwd",
          "info": "CANCELLED",
          "test": 1,
          "margin": 0.06,
          "earnings": 0
        },
        {
          "id": 47,
          "cptyName": "Nokia",
          "Pair": "USDEUR",
          "date": "2018/7/2 9:27:34",
          "side": "sell",
          "riskAmount": 726482958,
          "status": "OC",
          "type": "swp",
          "info": "CANCELLED",
          "test": 2,
          "margin": 0.08,
          "earnings": 0
        },
        {
          "id": 48,
          "cptyName": "Nokia",
          "Pair": "USDEUR",
          "date": "2018/8/24 2:8:34",
          "side": "buy",
          "riskAmount": 797356019,
          "status": "OC",
          "type": "sp",
          "info": "CANCELLED",
          "test": 3,
          "margin": 0.06,
          "earnings": 0
        },
        {
          "id": 49,
          "cptyName": "Nokia",
          "Pair": "USDSEK",
          "date": "2018/1/30 12:18:47",
          "side": "sell",
          "riskAmount": 827019063,
          "status": "OC",
          "type": "fwd",
          "info": "CANCELLED",
          "test": 4,
          "margin": 0.1,
          "earnings": 0
        },
        {
          "id": 50,
          "cptyName": "Nokia",
          "Pair": "USDSEK",
          "date": "2018/2/6 4:18:56",
          "side": "buy",
          "riskAmount": 382791908,
          "status": "OC",
          "type": "swp",
          "info": "CANCELLED",
          "test": 5,
          "margin": 0.08,
          "earnings": 0
        },
        {
          "id": 51,
          "cptyName": "Nokia",
          "Pair": "USDEUR",
          "date": "2018/8/4 4:59:29",
          "side": "sell",
          "riskAmount": 26396998,
          "status": "OC",
          "type": "sp",
          "info": "CANCELLED",
          "test": 6,
          "margin": 0.04,
          "earnings": 0
        },
        {
          "id": 52,
          "cptyName": "Nokia",
          "Pair": "USDEUR",
          "date": "2018/3/28 2:39:26",
          "side": "buy",
          "riskAmount": 28792159,
          "status": "OC",
          "type": "fwd",
          "info": "CANCELLED",
          "test": 7,
          "margin": 0.04,
          "earnings": 0
        },
        {
          "id": 53,
          "cptyName": "Nokia",
          "Pair": "EURSEK",
          "date": "2018/9/16 7:48:31",
          "side": "sell",
          "riskAmount": 622459723,
          "status": "OC",
          "type": "swp",
          "info": "CANCELLED",
          "test": 8,
          "margin": 0.04,
          "earnings": 0
        },
        {
          "id": 54,
          "cptyName": "Nokia",
          "Pair": "USDSEK",
          "date": "2018/2/14 8:54:14",
          "side": "buy",
          "riskAmount": 345564403,
          "status": "OC",
          "type": "sp",
          "info": "CANCELLED",
          "test": 9,
          "margin": 0.09,
          "earnings": 0
        },
        {
          "id": 55,
          "cptyName": "Nokia",
          "Pair": "USDEUR",
          "date": "2018/6/7 22:34:19",
          "side": "sell",
          "riskAmount": 291644961,
          "status": "OC",
          "type": "fwd",
          "info": "CANCELLED",
          "test": 10,
          "margin": 0.01,
          "earnings": 0
        },
        {
          "id": 56,
          "cptyName": "Nokia",
          "Pair": "USDEUR",
          "date": "2018/11/21 17:37:53",
          "side": "buy",
          "riskAmount": 415389804,
          "status": "OC",
          "type": "swp",
          "info": "UNKNOWN",
          "test": 20,
          "margin": 0.04,
          "earnings": 0
        },
        {
          "id": 57,
          "cptyName": "Nokia",
          "Pair": "EURSEK",
          "date": "2018/11/11 7:20:21",
          "side": "sell",
          "riskAmount": 670083685,
          "status": "OC",
          "type": "sp",
          "info": "UNKNOWN",
          "test": 30,
          "margin": 0.01,
          "earnings": 0
        },
        {
          "id": 58,
          "cptyName": "Nokia",
          "Pair": "SEKUSD",
          "date": "2018/8/25 3:22:31",
          "side": "buy",
          "riskAmount": 681995041,
          "status": "OC",
          "type": "fwd",
          "info": "UNKNOWN",
          "test": 40,
          "margin": 0.1,
          "earnings": 0
        },
        {
          "id": 59,
          "cptyName": "Nokia",
          "Pair": "EURSEK",
          "date": "2018/11/12 8:55:52",
          "side": "sell",
          "riskAmount": 475122495,
          "status": "OC",
          "type": "swp",
          "info": "UNKNOWN",
          "test": 50,
          "margin": 0.06,
          "earnings": 0
        },
        {
          "id": 60,
          "cptyName": "Nokia",
          "Pair": "USDEUR",
          "date": "2018/12/10 0:35:44",
          "side": "buy",
          "riskAmount": 100170650,
          "status": "OC",
          "type": "sp",
          "info": "UNKNOWN",
          "test": 60,
          "margin": 0.04,
          "earnings": 0
        },
        {
          "id": 61,
          "cptyName": "Nokia",
          "Pair": "USDSEK",
          "date": "2018/9/24 24:28:43",
          "side": "sell",
          "riskAmount": 267428483,
          "status": "OC",
          "type": "fwd",
          "info": "UNKNOWN",
          "test": 70,
          "margin": 0.02,
          "earnings": 0
        },
        {
          "id": 62,
          "cptyName": "Nokia",
          "Pair": "USDEUR",
          "date": "2018/7/1 5:8:22",
          "side": "buy",
          "riskAmount": 344664006,
          "status": "OC",
          "type": "swp",
          "info": "UNKNOWN",
          "test": 80,
          "margin": 0.06,
          "earnings": 0
        },
        {
          "id": 63,
          "cptyName": "Nokia",
          "Pair": "SEKUSD",
          "date": "2018/4/27 16:23:9",
          "side": "sell",
          "riskAmount": 180458000,
          "status": "OD",
          "type": "sp",
          "info": "",
          "test": 90,
          "margin": 0.07,
          "earnings": 12632060
        },
        {
          "id": 64,
          "cptyName": "Nokia",
          "Pair": "USDSEK",
          "date": "2018/12/17 8:2:29",
          "side": "sell",
          "riskAmount": 929497996,
          "status": "OD",
          "type": "fwd",
          "info": "",
          "test": 100,
          "margin": 0.1,
          "earnings": 92949799.6
        },
        {
          "id": 65,
          "cptyName": "Nokia",
          "Pair": "USDSEK",
          "date": "2018/8/19 18:18:30",
          "side": "buy",
          "riskAmount": 363189953,
          "status": "OD",
          "type": "swp",
          "info": "",
          "test": 200,
          "margin": 0.02,
          "earnings": 7263799.06
        },
        {
          "id": 66,
          "cptyName": "Nokia",
          "Pair": "EURUSD",
          "date": "2018/2/7 15:57:39",
          "side": "sell",
          "riskAmount": 341516000,
          "status": "OD",
          "type": "sp",
          "info": "",
          "test": 300,
          "margin": 0.07,
          "earnings": 23906120
        },
        {
          "id": 67,
          "cptyName": "Nokia",
          "Pair": "USDEUR",
          "date": "2018/4/24 9:13:1",
          "side": "buy",
          "riskAmount": 373213629,
          "status": "OD",
          "type": "fwd",
          "info": "",
          "test": 400,
          "margin": 0.06,
          "earnings": 22392817.74
        },
        {
          "id": 68,
          "cptyName": "Nokia",
          "Pair": "USDEUR",
          "date": "2018/12/3 0:59:40",
          "side": "sell",
          "riskAmount": 25198343,
          "status": "OD",
          "type": "swp",
          "info": "",
          "test": 500,
          "margin": 0.07,
          "earnings": 1763884.01
        },
        {
          "id": 69,
          "cptyName": "Nokia",
          "Pair": "USDEUR",
          "date": "2018/10/13 1:8:23",
          "side": "buy",
          "riskAmount": 762190163,
          "status": "OD",
          "type": "sp",
          "info": "",
          "test": 600,
          "margin": 0.09,
          "earnings": 68597114.67
        },
        {
          "id": 70,
          "cptyName": "Nokia",
          "Pair": "SEKUSD",
          "date": "2018/2/16 8:53:8",
          "side": "sell",
          "riskAmount": 759331519,
          "status": "OD",
          "type": "fwd",
          "info": "",
          "test": 700,
          "margin": 0.09,
          "earnings": 68339836.71
        },
        {
          "id": 71,
          "cptyName": "Nokia",
          "Pair": "USDEUR",
          "date": "2018/11/21 7:21:15",
          "side": "buy",
          "riskAmount": 854493902,
          "status": "OD",
          "type": "swp",
          "info": "",
          "test": 800,
          "margin": 0.03,
          "earnings": 25634817.06
        },
        {
          "id": 72,
          "cptyName": "Nokia",
          "Pair": "USDEUR",
          "date": "2018/4/15 6:32:33",
          "side": "sell",
          "riskAmount": 664652396,
          "status": "OD",
          "type": "sp",
          "info": "",
          "test": 900,
          "margin": 0.09,
          "earnings": 59818715.64
        },
        {
          "id": 73,
          "cptyName": "Telia",
          "Pair": "SEKUSD",
          "date": "2018/5/3 4:31:51",
          "side": "buy",
          "riskAmount": 797211179,
          "status": "OC",
          "type": "fwd",
          "info": "RULE",
          "test": 0.1,
          "margin": 0.06,
          "earnings": 0
        },
        {
          "id": 74,
          "cptyName": "Telia",
          "Pair": "USDSEK",
          "date": "2018/12/21 22:53:8",
          "side": "sell",
          "riskAmount": 515249129,
          "status": "OC",
          "type": "swp",
          "info": "RULE",
          "test": 0.2,
          "margin": 0.03,
          "earnings": 0
        },
        {
          "id": 75,
          "cptyName": "Telia",
          "Pair": "EURSEK",
          "date": "2018/9/5 9:7:29",
          "side": "buy",
          "riskAmount": 676473575,
          "status": "OC",
          "type": "sp",
          "info": "RULE",
          "test": 0.3,
          "margin": 0.05,
          "earnings": 0
        },
        {
          "id": 76,
          "cptyName": "Telia",
          "Pair": "USDSEK",
          "date": "2018/8/8 0:17:20",
          "side": "sell",
          "riskAmount": 896936890,
          "status": "OC",
          "type": "fwd",
          "info": "RULE",
          "test": 0.4,
          "margin": 0.07,
          "earnings": 0
        },
        {
          "id": 77,
          "cptyName": "Telia",
          "Pair": "EURSEK",
          "date": "2018/5/6 19:27:40",
          "side": "buy",
          "riskAmount": 286792263,
          "status": "OC",
          "type": "swp",
          "info": "RULE",
          "test": 0.5,
          "margin": 0.01,
          "earnings": 0
        },
        {
          "id": 78,
          "cptyName": "Telia",
          "Pair": "EURUSD",
          "date": "2018/12/30 22:34:45",
          "side": "sell",
          "riskAmount": 346050327,
          "status": "OC",
          "type": "sp",
          "info": "RULE",
          "test": 0.6,
          "margin": 0.09,
          "earnings": 0
        },
        {
          "id": 79,
          "cptyName": "Telia",
          "Pair": "SEKUSD",
          "date": "2018/8/22 3:19:9",
          "side": "buy",
          "riskAmount": 614883792,
          "status": "OC",
          "type": "fwd",
          "info": "RULE",
          "test": 0.7,
          "margin": 0.09,
          "earnings": 0
        },
        {
          "id": 80,
          "cptyName": "Telia",
          "Pair": "EURUSD",
          "date": "2018/11/16 16:22:12",
          "side": "sell",
          "riskAmount": 870923627,
          "status": "OC",
          "type": "swp",
          "info": "CANCELLED",
          "test": 0.8,
          "margin": 0.1,
          "earnings": 0
        },
        {
          "id": 81,
          "cptyName": "Telia",
          "Pair": "EURSEK",
          "date": "2018/3/6 5:48:1",
          "side": "buy",
          "riskAmount": 241571472,
          "status": "OC",
          "type": "sp",
          "info": "CANCELLED",
          "test": 0.9,
          "margin": 0.01,
          "earnings": 0
        },
        {
          "id": 82,
          "cptyName": "Telia",
          "Pair": "EURSEK",
          "date": "2018/8/22 14:37:41",
          "side": "buy",
          "riskAmount": 960116186,
          "status": "OC",
          "type": "fwd",
          "info": "CANCELLED",
          "test": 1,
          "margin": 0.1,
          "earnings": 0
        },
        {
          "id": 83,
          "cptyName": "Telia",
          "Pair": "USDEUR",
          "date": "2018/4/23 16:2:49",
          "side": "sell",
          "riskAmount": 393576420,
          "status": "OC",
          "type": "swp",
          "info": "CANCELLED",
          "test": 2,
          "margin": 0.05,
          "earnings": 0
        },
        {
          "id": 84,
          "cptyName": "Telia",
          "Pair": "USDEUR",
          "date": "2018/5/28 4:38:8",
          "side": "buy",
          "riskAmount": 21431756,
          "status": "OC",
          "type": "sp",
          "info": "CANCELLED",
          "test": 3,
          "margin": 0.05,
          "earnings": 0
        },
        {
          "id": 85,
          "cptyName": "Telia",
          "Pair": "USDSEK",
          "date": "2018/2/27 11:41:17",
          "side": "sell",
          "riskAmount": 193480693,
          "status": "OC",
          "type": "fwd",
          "info": "CANCELLED",
          "test": 4,
          "margin": 0.03,
          "earnings": 0
        },
        {
          "id": 86,
          "cptyName": "Telia",
          "Pair": "USDSEK",
          "date": "2018/1/1 18:38:31",
          "side": "buy",
          "riskAmount": 901023821,
          "status": "OC",
          "type": "swp",
          "info": "CANCELLED",
          "test": 5,
          "margin": 0.08,
          "earnings": 0
        },
        {
          "id": 87,
          "cptyName": "Telia",
          "Pair": "USDEUR",
          "date": "2018/9/18 0:13:20",
          "side": "sell",
          "riskAmount": 760513777,
          "status": "OC",
          "type": "sp",
          "info": "CANCELLED",
          "test": 6,
          "margin": 0.08,
          "earnings": 0
        },
        {
          "id": 88,
          "cptyName": "Telia",
          "Pair": "USDEUR",
          "date": "2018/3/3 10:42:27",
          "side": "buy",
          "riskAmount": 936883639,
          "status": "OC",
          "type": "fwd",
          "info": "CANCELLED",
          "test": 7,
          "margin": 0.07,
          "earnings": 0
        },
        {
          "id": 89,
          "cptyName": "Telia",
          "Pair": "EURSEK",
          "date": "2018/9/22 16:43:22",
          "side": "sell",
          "riskAmount": 692043578,
          "status": "OC",
          "type": "swp",
          "info": "CANCELLED",
          "test": 8,
          "margin": 0.04,
          "earnings": 0
        },
        {
          "id": 90,
          "cptyName": "Telia",
          "Pair": "USDSEK",
          "date": "2018/7/16 2:34:10",
          "side": "buy",
          "riskAmount": 877901837,
          "status": "OC",
          "type": "sp",
          "info": "CANCELLED",
          "test": 9,
          "margin": 0.02,
          "earnings": 0
        },
        {
          "id": 91,
          "cptyName": "Telia",
          "Pair": "USDEUR",
          "date": "2018/9/11 1:6:2",
          "side": "sell",
          "riskAmount": 148772220,
          "status": "OC",
          "type": "fwd",
          "info": "CANCELLED",
          "test": 10,
          "margin": 0.07,
          "earnings": 0
        },
        {
          "id": 92,
          "cptyName": "Telia",
          "Pair": "USDEUR",
          "date": "2018/10/23 17:36:18",
          "side": "buy",
          "riskAmount": 828734793,
          "status": "OC",
          "type": "swp",
          "info": "UNKNOWN",
          "test": 20,
          "margin": 0.1,
          "earnings": 0
        },
        {
          "id": 93,
          "cptyName": "Telia",
          "Pair": "EURSEK",
          "date": "2018/7/21 16:9:49",
          "side": "sell",
          "riskAmount": 868496971,
          "status": "OC",
          "type": "sp",
          "info": "UNKNOWN",
          "test": 30,
          "margin": 0.06,
          "earnings": 0
        },
        {
          "id": 94,
          "cptyName": "Telia",
          "Pair": "SEKUSD",
          "date": "2018/5/15 10:45:27",
          "side": "buy",
          "riskAmount": 786766332,
          "status": "OC",
          "type": "fwd",
          "info": "UNKNOWN",
          "test": 40,
          "margin": 0.09,
          "earnings": 0
        },
        {
          "id": 95,
          "cptyName": "Telia",
          "Pair": "EURSEK",
          "date": "2018/6/6 13:28:26",
          "side": "sell",
          "riskAmount": 617098513,
          "status": "OC",
          "type": "swp",
          "info": "UNKNOWN",
          "test": 50,
          "margin": 0.08,
          "earnings": 0
        },
        {
          "id": 96,
          "cptyName": "Telia",
          "Pair": "USDEUR",
          "date": "2018/3/20 7:44:54",
          "side": "buy",
          "riskAmount": 83133755,
          "status": "OC",
          "type": "sp",
          "info": "UNKNOWN",
          "test": 60,
          "margin": 0.01,
          "earnings": 0
        },
        {
          "id": 97,
          "cptyName": "Telia",
          "Pair": "USDSEK",
          "date": "2018/12/29 1:22:53",
          "side": "sell",
          "riskAmount": 15297482,
          "status": "OC",
          "type": "fwd",
          "info": "UNKNOWN",
          "test": 70,
          "margin": 0.02,
          "earnings": 0
        },
        {
          "id": 98,
          "cptyName": "Telia",
          "Pair": "USDEUR",
          "date": "2018/3/6 8:39:4",
          "side": "buy",
          "riskAmount": 38378506,
          "status": "OC",
          "type": "swp",
          "info": "UNKNOWN",
          "test": 80,
          "margin": 0.05,
          "earnings": 0
        },
        {
          "id": 99,
          "cptyName": "Telia",
          "Pair": "SEKUSD",
          "date": "2018/4/4 15:58:24",
          "side": "sell",
          "riskAmount": 778642960,
          "status": "OD",
          "type": "sp",
          "info": "",
          "test": 90,
          "margin": 0.1,
          "earnings": 77864296
        },
        {
          "id": 100,
          "cptyName": "Telia",
          "Pair": "USDSEK",
          "date": "2018/12/21 11:48:18",
          "side": "sell",
          "riskAmount": 215519559,
          "status": "OD",
          "type": "fwd",
          "info": "",
          "test": 100,
          "margin": 0.05,
          "earnings": 10775977.95
        },
        {
          "id": 101,
          "cptyName": "Telia",
          "Pair": "USDSEK",
          "date": "2018/9/18 11:28:53",
          "side": "buy",
          "riskAmount": 98861185,
          "status": "OD",
          "type": "swp",
          "info": "",
          "test": 200,
          "margin": 0.07,
          "earnings": 6920282.95
        },
        {
          "id": 102,
          "cptyName": "Telia",
          "Pair": "EURUSD",
          "date": "2018/9/2 23:39:44",
          "side": "sell",
          "riskAmount": 506987593,
          "status": "OD",
          "type": "sp",
          "info": "",
          "test": 300,
          "margin": 0.03,
          "earnings": 15209627.79
        },
        {
          "id": 103,
          "cptyName": "Telia",
          "Pair": "USDEUR",
          "date": "2018/6/10 14:53:59",
          "side": "buy",
          "riskAmount": 103247293,
          "status": "OD",
          "type": "fwd",
          "info": "",
          "test": 400,
          "margin": 0.1,
          "earnings": 10324729.3
        },
        {
          "id": 104,
          "cptyName": "Telia",
          "Pair": "USDEUR",
          "date": "2018/3/30 8:4:33",
          "side": "sell",
          "riskAmount": 535052292,
          "status": "OD",
          "type": "swp",
          "info": "",
          "test": 500,
          "margin": 0.05,
          "earnings": 26752614.6
        },
        {
          "id": 105,
          "cptyName": "Telia",
          "Pair": "USDEUR",
          "date": "2018/3/30 24:44:31",
          "side": "buy",
          "riskAmount": 937131231,
          "status": "OD",
          "type": "sp",
          "info": "",
          "test": 600,
          "margin": 0.07,
          "earnings": 65599186.17
        },
        {
          "id": 106,
          "cptyName": "Telia",
          "Pair": "SEKUSD",
          "date": "2018/8/17 19:56:44",
          "side": "sell",
          "riskAmount": 6775932,
          "status": "OD",
          "type": "fwd",
          "info": "",
          "test": 700,
          "margin": 0.05,
          "earnings": 338796.6
        },
        {
          "id": 107,
          "cptyName": "Telia",
          "Pair": "USDEUR",
          "date": "2018/11/11 8:6:14",
          "side": "buy",
          "riskAmount": 325535267,
          "status": "OD",
          "type": "swp",
          "info": "",
          "test": 800,
          "margin": 0.02,
          "earnings": 6510705.34
        },
        {
          "id": 108,
          "cptyName": "Telia",
          "Pair": "USDEUR",
          "date": "2018/5/30 9:12:29",
          "side": "sell",
          "riskAmount": 590910895,
          "status": "OD",
          "type": "sp",
          "info": "",
          "test": 900,
          "margin": 0.04,
          "earnings": 23636435.8
        },
        {
          "id": 109,
          "cptyName": "Telia",
          "Pair": "JPYAUD",
          "date": "2018/5/11 9:12:29",
          "side": "sell",
          "riskAmount": 590910895,
          "status": "OD",
          "type": "sp",
          "info": "",
          "test": 900,
          "margin": 0.04,
          "earnings": 23636435.8
        },
        {
          "id": 110,
          "cptyName": "Telia",
          "Pair": "JPYEUR",
          "date": "2018/5/23 9:12:29",
          "side": "sell",
          "riskAmount": 590910895,
          "status": "OD",
          "type": "sp",
          "info": "",
          "test": 900,
          "margin": 0.04,
          "earnings": 23636435.8
        },
        {
          "id": 111,
          "cptyName": "Telia",
          "Pair": "AUDSEK",
          "date": "2018/5/23 9:12:29",
          "side": "sell",
          "riskAmount": 590910895,
          "status": "OD",
          "type": "sp",
          "info": "",
          "test": 900,
          "margin": 0.04,
          "earnings": 23636435.8
        }
      ]

  export default testData;